openapi: 3.0.0
info:
    description: Biolerplate express
    version: 1.0.0
    title: Boilerplate Express
paths:
    /users:
        get:
            tags:
                - Get Users
            description: Get All data Users
            security:
                - BearerAuth: []
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    description:
                                        type: string
                                    result:
                                        type: object
        post:
            tags:
                - Add Users
            description: Insert new Users data
            security:
                - BasicAuth: []
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                fullName:
                                    type: string
                                    example: user1
                                email:
                                    type: string
                                    example: user1@email.com
                                Address:
                                    type: string
                                    example: tebet utara
                                Username:
                                    type: string
                                    example: theone
                                Password:
                                    type: string
                                    example: Password
                                RePassword:
                                    type: string
                                    example: Password
                            required:
                                - fullName
                                - email
                                - Username
                                - Password
                                - RePassword
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                properties:
                                    status:
                                        type: integer
                                        example: 200
                                    description:
                                        type: string
                                        example: ok
                                    result:
                                        type: object
