apiVersion: v1
kind: Namespace
metadata:
  name: rentproject
---
apiVersion: v1
data:
  PGHOST: "52.77.251.231"
  PGUSER: "bukanebi"
  PGDATABASE: "Rentapp"
  PGPASSWORD: "bukalapak"
  PGPORT: "5439"
  SERVICEPORT: "9000"
  MODE: "Dev"

kind: ConfigMap
metadata:
  name: reantapp-maps
  namespace: rentproject

---
apiVersion: v1
kind: Service
metadata:
  name: reantapp-service
  namespace: rentproject
  labels:
    app: user-services
    tier: backend
spec:
  selector:
    app: user-services
    tier: backend
  type: LoadBalancer
  ports:
    - name: serviceport
      port: 9000
      targetPort: 9000
      nodePort: 31649

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reantapp-service
  namespace: rentproject
spec:
  selector:
    matchLabels:
      app: user-services
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-services
        tier: backend
    spec:
      containers:
        - name: user-service
          image: bukanebi/user-service-image
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: reantapp-maps
