---
- name: Create pods using deployment
  hosts: kubernetes
  user: admin
  vars:
    deployFile: user-service-k8s.yaml

  tasks:
    - name: copy k8s yml file to master node
      copy:
        src: /opt/project/{{deployFile}}
        dest: /home/admin/{{deployFile}}
        owner: admin
      ignore_errors: yes

    - name: create a deployment
      command: kubectl apply -f {{deployFile}}
